name: publish

on:
  push:
    tags:
      - '*'
  pull_request:


jobs:

  build:

    runs-on: ubuntu-latest
      
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v5.0.0
      with:
        images: imteksim/jupyterlab-surfacetopography
        tags: |
          type=raw,value=latest
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache docker layers
      uses: actions/cache@v3.3.1
      env:
        cache-name: cache-docker-layers
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ env.cache-name }}

    # prepare publication on dockerhub if tagged
    - name: Login to DockerHub
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # build image locally, push to dockerhub if tagged
    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: ./docker
        file: ./docker/jupyterlab-SurfaceTopography/Dockerfile
        platforms: linux/amd64
        push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
